/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade1.Tela;

import atividade1.Vo.Produto;
import atividade1.Vo.Venda;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class frameTela extends javax.swing.JFrame {

    /**
     * Creates new form frameTela
     */
    public frameTela() {
        initComponents();
    }

    private void limparCamposVenda(){
        fieldNumVenda.setText(null);
    }
    
    private void limparCampos(){
        fieldCodProd.setText(null);
        fieldNomeProd.setText(null);
        fieldValorUnitProd.setText(null);
        fieldQntdProd.setText(null);
        fieldNumVenda.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePrincipal = new javax.swing.JInternalFrame();
        labelNumVenda = new javax.swing.JLabel();
        fieldNumVenda = new javax.swing.JTextField();
        buttonEnviarVenda = new javax.swing.JButton();
        labelCodProd = new javax.swing.JLabel();
        fieldCodProd = new javax.swing.JTextField();
        labelNomeProd = new javax.swing.JLabel();
        fieldNomeProd = new javax.swing.JTextField();
        labelValorUnitProd = new javax.swing.JLabel();
        fieldValorUnitProd = new javax.swing.JTextField();
        labelQntdProd = new javax.swing.JLabel();
        fieldQntdProd = new javax.swing.JTextField();
        labelAvisoCampos = new javax.swing.JLabel();
        labelAvisoDesconto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        framePrincipal.setTitle("Realizar Venda");
        framePrincipal.setVisible(true);

        labelNumVenda.setText("Informe o número da venda:");

        fieldNumVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumVendaActionPerformed(evt);
            }
        });

        buttonEnviarVenda.setText("enviar venda");
        buttonEnviarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarVendaActionPerformed(evt);
            }
        });

        labelCodProd.setText("Informe o código do produto:");

        fieldCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodProdActionPerformed(evt);
            }
        });

        labelNomeProd.setText("Informe o nome do produto:");

        labelValorUnitProd.setText("Informe o valor unitário do produto:");

        labelQntdProd.setText("Informe a quantidade de produtos:");

        labelAvisoCampos.setText("Preencha todos os campos antes de enviar a venda !!!");

        labelAvisoDesconto.setText("O desconto já é calculado automaticamente !");

        javax.swing.GroupLayout framePrincipalLayout = new javax.swing.GroupLayout(framePrincipal.getContentPane());
        framePrincipal.getContentPane().setLayout(framePrincipalLayout);
        framePrincipalLayout.setHorizontalGroup(
            framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePrincipalLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(buttonEnviarVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(framePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framePrincipalLayout.createSequentialGroup()
                        .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(framePrincipalLayout.createSequentialGroup()
                                .addComponent(labelNomeProd)
                                .addGap(50, 71, Short.MAX_VALUE))
                            .addGroup(framePrincipalLayout.createSequentialGroup()
                                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodProd, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addGroup(framePrincipalLayout.createSequentialGroup()
                                        .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldQntdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQntdProd)
                            .addComponent(labelValorUnitProd)
                            .addComponent(fieldValorUnitProd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePrincipalLayout.createSequentialGroup()
                                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNumVenda))
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePrincipalLayout.createSequentialGroup()
                                .addComponent(labelAvisoDesconto)
                                .addGap(94, 94, 94))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAvisoCampos)
                .addGap(68, 68, 68))
        );
        framePrincipalLayout.setVerticalGroup(
            framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNumVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodProd)
                    .addComponent(labelValorUnitProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldValorUnitProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeProd)
                    .addComponent(labelQntdProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldQntdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonEnviarVenda)
                .addGap(18, 18, 18)
                .addComponent(labelAvisoCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAvisoDesconto)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNumVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumVendaActionPerformed

    private void buttonEnviarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarVendaActionPerformed
        // TODO add your handling code here:
        Venda venda = new Venda();
        venda.setNumeroDaVenda(Integer.parseInt(fieldNumVenda.getText()));
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
        venda.setData(data);
        venda.setHora(hora);
        venda.setValorTotalDeVenda(venda.descontoPorQuantidade((int) Float.parseFloat(fieldQntdProd.getText())));
        venda.gravarVenda(venda);
        Produto produto = new Produto();
        produto.setCodigo(Integer.parseInt(fieldCodProd.getText()));
        produto.setNome(fieldNomeProd.getText());
        produto.setValorUnitario(Float.parseFloat(fieldValorUnitProd.getText()));
        venda.gravarProduto(produto);
        JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!");
        limparCampos();
    }//GEN-LAST:event_buttonEnviarVendaActionPerformed

    private void fieldCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviarVenda;
    private javax.swing.JTextField fieldCodProd;
    private javax.swing.JTextField fieldNomeProd;
    private javax.swing.JTextField fieldNumVenda;
    private javax.swing.JTextField fieldQntdProd;
    private javax.swing.JTextField fieldValorUnitProd;
    private javax.swing.JInternalFrame framePrincipal;
    private javax.swing.JLabel labelAvisoCampos;
    private javax.swing.JLabel labelAvisoDesconto;
    private javax.swing.JLabel labelCodProd;
    private javax.swing.JLabel labelNomeProd;
    private javax.swing.JLabel labelNumVenda;
    private javax.swing.JLabel labelQntdProd;
    private javax.swing.JLabel labelValorUnitProd;
    // End of variables declaration//GEN-END:variables
}
