/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerClientes;
import controller.ControllerProdutos;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasCliente;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.Datas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelClientes;
import model.ModelProdutos;
import model.ModelProdutosVendasProdutos;
import model.ModelVendas;
import model.ModelVendasCliente;
import model.ModelVendasProdutos;

/**
 *
 * @author luan0
 */
public class ViewVendas extends javax.swing.JFrame {

    ControllerClientes controllerCliente = new ControllerClientes();
    ModelClientes modelClientes = new ModelClientes();
    ArrayList<ModelClientes> listaModelClientes = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ArrayList<ModelVendasCliente> listaModelVendasClientes = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVendas controllerVendas = new ControllerVendas();
    String txt, txt2;
    // Double txt2;
    ModelVendas modelVendas = new ModelVendas();
    Datas datas = new Datas();
    ControllerVendasCliente controllerVendasCliente1 = new ControllerVendasCliente();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ModelProdutosVendasProdutos modelProdutosVendasProdutos = new ModelProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasProdutos = new ArrayList<>();
    ArrayList<ModelVendas> listaModelVendas = new ArrayList<>();
    ModelVendasCliente modelVendasCliente = new ModelVendasCliente();
    String alterarSalvar;

    

    /**
     * Creates new form ViewVendas
     */
    public ViewVendas() {
        initComponents();
        listarClientes();
        listarProdutos();
        setLocationRelativeTo(null);
        carregarVendas();
        preencherCodigoClientePeloComboBox();
        preencherCodigoProdutoPeloComboBox();
        habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JTabbedPane();
        Cadastro = new javax.swing.JPanel();
        CodigoClienteTxt1 = new javax.swing.JTextField();
        CodigoCliente = new javax.swing.JLabel();
        NCliente1 = new javax.swing.JLabel();
        NumVenda1 = new javax.swing.JLabel();
        CdProd1 = new javax.swing.JLabel();
        Qntd1 = new javax.swing.JLabel();
        AddBt1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProdutosVenda1 = new javax.swing.JTable();
        CancelarBt1 = new javax.swing.JButton();
        NovoBt1 = new javax.swing.JButton();
        SalvarBt1 = new javax.swing.JButton();
        VlrTotal1 = new javax.swing.JLabel();
        VlrTotalTxt1 = new javax.swing.JTextField();
        DescontoTxt1 = new javax.swing.JTextField();
        Desconto1 = new javax.swing.JLabel();
        QntdTxt1 = new javax.swing.JTextField();
        NomeCliCBX = new javax.swing.JComboBox<>();
        ProdutoCbx = new javax.swing.JComboBox<>();
        CdProdTxt = new javax.swing.JTextField();
        NumVenTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CEA = new javax.swing.JPanel();
        Pesquisa = new javax.swing.JLabel();
        PesquisaTxt = new javax.swing.JTextField();
        PesquisarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVendas = new javax.swing.JTable();
        ExcluirBt = new javax.swing.JButton();
        AlterarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);

        CodigoClienteTxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CodigoClienteTxt1FocusLost(evt);
            }
        });
        CodigoClienteTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoClienteTxt1ActionPerformed(evt);
            }
        });

        CodigoCliente.setText("Código Cliente");

        NCliente1.setText("Nome do Cliente:");

        NumVenda1.setText("Número da Venda:");

        CdProd1.setText("Cod. Produto");

        Qntd1.setText("Quantidade:");

        AddBt1.setText("Adicionar");
        AddBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBt1ActionPerformed(evt);
            }
        });

        TabelaProdutosVenda1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod", "Nome Produto", "Quantidade", "Valor Unt.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaProdutosVenda1);
        if (TabelaProdutosVenda1.getColumnModel().getColumnCount() > 0) {
            TabelaProdutosVenda1.getColumnModel().getColumn(0).setMinWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(0).setPreferredWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(0).setMaxWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(2).setMinWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(2).setPreferredWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(2).setMaxWidth(70);
            TabelaProdutosVenda1.getColumnModel().getColumn(3).setMinWidth(90);
            TabelaProdutosVenda1.getColumnModel().getColumn(3).setPreferredWidth(90);
            TabelaProdutosVenda1.getColumnModel().getColumn(3).setMaxWidth(90);
            TabelaProdutosVenda1.getColumnModel().getColumn(4).setMinWidth(90);
            TabelaProdutosVenda1.getColumnModel().getColumn(4).setPreferredWidth(90);
            TabelaProdutosVenda1.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        CancelarBt1.setText("Cancelar");
        CancelarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBt1ActionPerformed(evt);
            }
        });

        NovoBt1.setText("Novo");
        NovoBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoBt1ActionPerformed(evt);
            }
        });

        SalvarBt1.setText("Salvar");
        SalvarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBt1ActionPerformed(evt);
            }
        });

        VlrTotal1.setText("Valor Total:");

        VlrTotalTxt1.setEditable(false);

        DescontoTxt1.setEditable(false);
        DescontoTxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescontoTxt1FocusLost(evt);
            }
        });
        DescontoTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescontoTxt1ActionPerformed(evt);
            }
        });

        Desconto1.setText("Desconto:");

        QntdTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QntdTxt1ActionPerformed(evt);
            }
        });

        NomeCliCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NomeCliCBX.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                NomeCliCBXPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        NomeCliCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCliCBXActionPerformed(evt);
            }
        });

        ProdutoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProdutoCbx.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ProdutoCbxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        CdProdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CdProdTxtFocusLost(evt);
            }
        });

        jLabel1.setText("Nome do Produto:");

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroLayout.createSequentialGroup()
                                .addComponent(CodigoCliente)
                                .addGap(21, 21, 21)
                                .addComponent(NCliente1)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumVenda1)
                                    .addComponent(VlrTotal1)
                                    .addComponent(VlrTotalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CadastroLayout.createSequentialGroup()
                                .addComponent(CancelarBt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NovoBt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalvarBt1)))
                        .addContainerGap())
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CdProdTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoClienteTxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(CdProd1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NomeCliCBX, 0, 478, Short.MAX_VALUE)
                                .addComponent(ProdutoCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroLayout.createSequentialGroup()
                                .addComponent(NumVenTxt)
                                .addGap(71, 71, 71))
                            .addGroup(CadastroLayout.createSequentialGroup()
                                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescontoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Desconto1)
                                    .addGroup(CadastroLayout.createSequentialGroup()
                                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(QntdTxt1)
                                            .addComponent(Qntd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddBt1)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCliente)
                    .addComponent(NCliente1)
                    .addComponent(NumVenda1))
                .addGap(8, 8, 8)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoClienteTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeCliCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumVenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CdProd1)
                    .addComponent(Qntd1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CdProdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QntdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBt1)
                    .addComponent(ProdutoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Desconto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescontoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(VlrTotal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VlrTotalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBt1)
                    .addComponent(NovoBt1)
                    .addComponent(SalvarBt1))
                .addGap(18, 18, 18))
        );

        PainelPrincipal.addTab("Cadastro", Cadastro);

        Pesquisa.setText("Pesquisa:");

        PesquisarBt.setText("Pesquisar");

        TabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Cliente", "Nome do Produto", "Qntd.", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaVendas);
        if (TabelaVendas.getColumnModel().getColumnCount() > 0) {
            TabelaVendas.getColumnModel().getColumn(0).setMinWidth(110);
            TabelaVendas.getColumnModel().getColumn(0).setPreferredWidth(110);
            TabelaVendas.getColumnModel().getColumn(0).setMaxWidth(110);
            TabelaVendas.getColumnModel().getColumn(3).setMinWidth(70);
            TabelaVendas.getColumnModel().getColumn(3).setPreferredWidth(70);
            TabelaVendas.getColumnModel().getColumn(3).setMaxWidth(70);
            TabelaVendas.getColumnModel().getColumn(4).setMinWidth(90);
            TabelaVendas.getColumnModel().getColumn(4).setPreferredWidth(90);
            TabelaVendas.getColumnModel().getColumn(4).setMaxWidth(90);
            TabelaVendas.getColumnModel().getColumn(5).setMinWidth(110);
            TabelaVendas.getColumnModel().getColumn(5).setPreferredWidth(110);
            TabelaVendas.getColumnModel().getColumn(5).setMaxWidth(110);
        }

        ExcluirBt.setText("Excluir");
        ExcluirBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtActionPerformed(evt);
            }
        });

        AlterarBt.setText("Alterar");
        AlterarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CEALayout = new javax.swing.GroupLayout(CEA);
        CEA.setLayout(CEALayout);
        CEALayout.setHorizontalGroup(
            CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CEALayout.createSequentialGroup()
                .addGroup(CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CEALayout.createSequentialGroup()
                        .addComponent(PesquisaTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesquisarBt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(CEALayout.createSequentialGroup()
                        .addGroup(CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pesquisa)
                            .addGroup(CEALayout.createSequentialGroup()
                                .addComponent(ExcluirBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AlterarBt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CEALayout.setVerticalGroup(
            CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CEALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarBt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(CEALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExcluirBt)
                    .addComponent(AlterarBt))
                .addContainerGap())
        );

        PainelPrincipal.addTab("Consultar/Excluir/Alterar", CEA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoClienteTxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodigoClienteTxt1FocusLost
        // TODO add your handling code here:
        modelClientes = controllerCliente.retornarClienteController(Integer.parseInt(CodigoClienteTxt1.getText()));
        NomeCliCBX.setSelectedItem(modelClientes.getCliNome());
    }//GEN-LAST:event_CodigoClienteTxt1FocusLost

    private void NomeCliCBXPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_NomeCliCBXPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (NomeCliCBX.isPopupVisible()) {
            preencherCodigoClientePeloComboBox();
        }
    }//GEN-LAST:event_NomeCliCBXPopupMenuWillBecomeInvisible

    private void ProdutoCbxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ProdutoCbxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (ProdutoCbx.isVisible()) {
            preencherCodigoProdutoPeloComboBox();
        }
    }//GEN-LAST:event_ProdutoCbxPopupMenuWillBecomeInvisible

    private void CdProdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CdProdTxtFocusLost
        // TODO add your handling code here:
        modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(CdProdTxt.getText()));
        ProdutoCbx.setSelectedItem(modelProdutos.getProNome());
    }//GEN-LAST:event_CdProdTxtFocusLost

    private void ExcluirBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtActionPerformed
        // TODO add your handling code here:
        
        habilitarDesabilitarCampos(false);
        int linha = TabelaVendas.getSelectedRow();
        int codigoVenda = (int) TabelaVendas.getValueAt(linha, 0);
        
        listaModelProdutos = new ArrayList<>();
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.retornarListaProdutosVendasProdutosController(codigoVenda);
        for (int i = 0; i < listaModelProdutosVendasProdutos.size(); i++) {
            modelProdutos = new ModelProdutos();
            modelProdutos.setIdProduto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getIdProduto());
            modelProdutos.setProEstoque(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getProEstoque());
                    //+ listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade());
            listaModelProdutos.add(modelProdutos);
        }

        if (controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos)) {
            controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
            if (controllerVendas.excluirVendasController(codigoVenda)) {
                JOptionPane.showMessageDialog(this, "Sucesso ao excluir venda!", "ATENÇÃo", JOptionPane.WARNING_MESSAGE);
                this.carregarVendas();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir venda!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir venda!", "ERRO", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_ExcluirBtActionPerformed

    private void AddBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBt1ActionPerformed
        // TODO add your handling code here:
        
        if (QntdTxt1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(CdProdTxt.getText()));
            DefaultTableModel modelo = (DefaultTableModel) TabelaProdutosVenda1.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(QntdTxt1.getText());
            if (quantidade < 10) {
                quantidade = quantidade;
            }
            if (quantidade >= 10 && quantidade < 20) {
                quantidade = quantidade - (quantidade * 0.05);
            }
            if (quantidade >= 20 && quantidade < 30) {
                quantidade = quantidade - (quantidade * 0.1);
            }
            if (quantidade >= 30) {
                quantidade = quantidade - (quantidade * 0.2);
            }
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }

            modelo.addRow(new Object[]{
                modelProdutos.getIdProduto(),
                modelProdutos.getProNome(),
                QntdTxt1.getText(),
                modelProdutos.getProValor(),
                quantidade * modelProdutos.getProValor()
            }
            );
            somarValorTotalProdutos();
            aplicarDescontosTabela();
            habilitarDesabilitarCampos(true);

        }
    }//GEN-LAST:event_AddBt1ActionPerformed

    private void DescontoTxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescontoTxt1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_DescontoTxt1FocusLost

    private void DescontoTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescontoTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescontoTxt1ActionPerformed

    private void NovoBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoBt1ActionPerformed
        // TODO add your handling code here:
        habilitarDesabilitarCampos(true);
        alterarSalvar = "novo";
        limparFormulario();
    }//GEN-LAST:event_NovoBt1ActionPerformed

    private void SalvarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBt1ActionPerformed
        // TODO add your handling code here:
        listaModelVendasProdutos = new ArrayList<>();
        modelVendas.setIdCliente(Integer.parseInt(CodigoClienteTxt1.getText()));
        int codigoVenda = 0, codigoProduto = 0;
        double quantidade = 0;
        quantidade = Double.parseDouble(QntdTxt1.getText());

        try {
            modelVendas.setVenDataVenda(datas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception e) {
        }
        modelVendas.setVenValorLiquido(Double.parseDouble(VlrTotalTxt1.getText()));
        modelVendas.setVenValorBruto((double) quantidade * modelProdutos.getProValor());
        modelVendas.setVenDesconto(Double.parseDouble(txt2));

        codigoVenda = controllerVendas.salvarVendasController(modelVendas);

        if (codigoVenda > 0) {
            JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro na venda!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        int cont = TabelaProdutosVenda1.getRowCount();
        for (int i = 0; i < cont; i++) {
            codigoProduto = (int) TabelaProdutosVenda1.getValueAt(i, 0);
            modelVendasProdutos = new ModelVendasProdutos();
            modelProdutos = new ModelProdutos();
            modelVendasProdutos.setIdProduto(codigoProduto);
            modelVendasProdutos.setIdVenda(codigoVenda);
            modelVendasProdutos.setVenProValor((double) TabelaProdutosVenda1.getValueAt(i, 3));
            modelVendasProdutos.setVenProQuantidade(Integer.parseInt(TabelaProdutosVenda1.getValueAt(i, 2).toString()));
            //produto
            modelProdutos.setIdProduto(codigoProduto);
            modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque()
                    - Integer.parseInt(TabelaProdutosVenda1.getValueAt(i, 2).toString()));
            listaModelVendasProdutos.add(modelVendasProdutos);
            listaModelProdutos.add(modelProdutos);
        }

        //salvar produtos da venda
        if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)) {
            //alterar estoque de produtos
            controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos);
            JOptionPane.showMessageDialog(this, "Produtos da venda salvos com sucesso!", "ATENÇÃ", JOptionPane.WARNING_MESSAGE);
            carregarVendas();
            limparFormulario();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar produtos da venda!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_SalvarBt1ActionPerformed

    private void AlterarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarBtActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "alterar";
        int linha = TabelaVendas.getSelectedRow();
        int codigoVenda = (int)(TabelaVendas.getValueAt(linha,0));
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.retornarListaProdutosVendasProdutosController(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) TabelaProdutosVenda1.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaModelProdutosVendasProdutos.size(); i++) {
            NumVenTxt.setText(String.valueOf(listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getIdVenda()));
            modelo.addRow(new Object[]
            {
              listaModelProdutosVendasProdutos.get(i).getModelProdutos().getIdProduto(),
              listaModelProdutosVendasProdutos.get(i).getModelProdutos().getProNome(),
              listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade(),
              listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProValor(),
              listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade()
              *listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProValor(),
            }
            );
        }
        somarValorTotalProdutos();
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_AlterarBtActionPerformed

    private void QntdTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QntdTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QntdTxt1ActionPerformed

    private void NomeCliCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCliCBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCliCBXActionPerformed

    private void CodigoClienteTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoClienteTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoClienteTxt1ActionPerformed

    private void CancelarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBt1ActionPerformed
        // TODO add your handling code here:
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_CancelarBt1ActionPerformed

    private void listarClientes() {
        listaModelClientes = controllerCliente.retornarListaClienteController();
        NomeCliCBX.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            NomeCliCBX.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void listarProdutos() {
        listaModelProdutos = controllerProdutos.retornarListaProdutoController();
        ProdutoCbx.removeAllItems();
        for (int i = 0; i < listaModelProdutos.size(); i++) {
            ProdutoCbx.addItem(listaModelProdutos.get(i).getProNome());
        }
    }
    
      private void habilitarDesabilitarCampos(boolean condicao){
        CdProdTxt.setEnabled(condicao);
        CodigoClienteTxt1.setEnabled(condicao);
        NomeCliCBX.setEnabled(condicao);
        ProdutoCbx.setEnabled(condicao);
        NumVenTxt.setEnabled(condicao);
        QntdTxt1.setEnabled(condicao);
        DescontoTxt1.setEnabled(condicao);
        AddBt1.setEnabled(condicao);
        SalvarBt1.setEnabled(condicao);
        VlrTotal1.setEnabled(condicao);
        
        
    }

    private void aplicarDescontosTabela() {
        double quantidade = 0;
        quantidade = Double.parseDouble(QntdTxt1.getText());
        if (quantidade < 10) {
            txt = "Sem desconto";
            txt2 = "0";
        }
        if (quantidade >= 10 && quantidade < 20) {
            txt = "5%";
            txt2 = "5";
        }
        if (quantidade >= 20 && quantidade < 30) {
            txt = "10%";
            txt2 = "10";
        }
        if (quantidade >= 30) {
            txt = "20%";
            txt2 = "20";
        }
        DescontoTxt1.setText(String.valueOf(txt));
    }

    private void somarValorTotalProdutos() {
        double soma = 0, valor;

        int cont = TabelaProdutosVenda1.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) TabelaProdutosVenda1.getValueAt(i, 4);
            soma += valor;
        }
        VlrTotalTxt1.setText(String.valueOf(soma));
    }

    private void preencherCodigoClientePeloComboBox() {
        modelClientes = controllerCliente.retornarClienteController(NomeCliCBX.getSelectedItem().toString());
        CodigoClienteTxt1.setText(String.valueOf(modelClientes.getIdCliente()));
    }

    private void preencherCodigoProdutoPeloComboBox() {
        modelProdutos = controllerProdutos.retornarProdutoController(ProdutoCbx.getSelectedItem().toString());
        CdProdTxt.setText(String.valueOf(modelProdutos.getIdProduto()));

    }

    private void limparFormulario() {
        QntdTxt1.setText("");
        DescontoTxt1.setText("");
        VlrTotalTxt1.setText("");
        DefaultTableModel modelo = (DefaultTableModel) TabelaProdutosVenda1.getModel();
        modelo.setNumRows(0);
    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.retornarListaVendasClienteController();
        listaModelProdutos = controllerProdutos.retornarListaProdutoController();   
        listaModelVendasProdutos = controllerVendasProdutos.retornarListaVendasProdutosController();
        int cont = listaModelVendasClientes.size();
        int cont2 = listaModelProdutos.size();
        int cont3 = listaModelVendasProdutos.size();
        modelo.setNumRows(0);
        for (int i = 0, j =0, k = 0; i < cont && j < cont2 && k < cont3; i++, j++, k++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelClientes().getCliNome(),
                listaModelProdutos.get(j).getProNome(),
                listaModelVendasProdutos.get(k).getVenProQuantidade(),
                listaModelVendasProdutos.get(k).getVenProValor(),
                listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda(),
                
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBt1;
    private javax.swing.JButton AlterarBt;
    private javax.swing.JPanel CEA;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JButton CancelarBt1;
    private javax.swing.JLabel CdProd1;
    private javax.swing.JTextField CdProdTxt;
    private javax.swing.JLabel CodigoCliente;
    private javax.swing.JTextField CodigoClienteTxt1;
    private javax.swing.JLabel Desconto1;
    private javax.swing.JTextField DescontoTxt1;
    private javax.swing.JButton ExcluirBt;
    private javax.swing.JLabel NCliente1;
    private javax.swing.JComboBox<String> NomeCliCBX;
    private javax.swing.JButton NovoBt1;
    private javax.swing.JTextField NumVenTxt;
    private javax.swing.JLabel NumVenda1;
    private javax.swing.JTabbedPane PainelPrincipal;
    private javax.swing.JLabel Pesquisa;
    private javax.swing.JTextField PesquisaTxt;
    private javax.swing.JButton PesquisarBt;
    private javax.swing.JComboBox<String> ProdutoCbx;
    private javax.swing.JLabel Qntd1;
    private javax.swing.JTextField QntdTxt1;
    private javax.swing.JButton SalvarBt1;
    private javax.swing.JTable TabelaProdutosVenda1;
    private javax.swing.JTable TabelaVendas;
    private javax.swing.JLabel VlrTotal1;
    private javax.swing.JTextField VlrTotalTxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
