/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProdutos;
import util.Formatador;

/**
 *
 * @author luan0
 */
public class ViewProduto extends javax.swing.JFrame {
    
    ArrayList<ModelProdutos> listaModelProduto = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    String salvarAlterar;
    Formatador formatador = new Formatador();
    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        CodigoTxt = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        NomeTxt = new javax.swing.JTextField();
        Estoque = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Pesquisar = new javax.swing.JLabel();
        PesquisarTxt = new javax.swing.JTextField();
        PesquisarBt = new javax.swing.JButton();
        CancelarBt = new javax.swing.JButton();
        NovoBt = new javax.swing.JButton();
        AlterarBt = new javax.swing.JButton();
        ExcluirBt = new javax.swing.JButton();
        SalvarBt = new javax.swing.JButton();
        EstoqueTxt = new javax.swing.JFormattedTextField();
        ValorTxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        Codigo.setText("Código:");

        CodigoTxt.setEditable(false);
        CodigoTxt.setEnabled(false);

        Nome.setText("Nome:");

        Estoque.setText("Estoque:");

        Valor.setText("Valor:");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Estoque", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(1).setMinWidth(300);
            Tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        Pesquisar.setText("Pesquisar:");

        PesquisarBt.setText("Pesquisar");
        PesquisarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarBtActionPerformed(evt);
            }
        });

        CancelarBt.setText("Cancelar");
        CancelarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtActionPerformed(evt);
            }
        });

        NovoBt.setText("Novo");
        NovoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoBtActionPerformed(evt);
            }
        });

        AlterarBt.setText("Alterar");
        AlterarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarBtActionPerformed(evt);
            }
        });

        ExcluirBt.setText("Excluir");
        ExcluirBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtActionPerformed(evt);
            }
        });

        SalvarBt.setText("Salvar");
        SalvarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBtActionPerformed(evt);
            }
        });

        EstoqueTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        EstoqueTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstoqueTxtActionPerformed(evt);
            }
        });

        ValorTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Codigo)
                    .addComponent(Estoque)
                    .addComponent(CodigoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(EstoqueTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valor)
                    .addComponent(Nome)
                    .addComponent(NomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarBt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CancelarBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirBt)
                        .addGap(3, 3, 3)
                        .addComponent(AlterarBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NovoBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalvarBt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estoque)
                    .addComponent(Valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstoqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pesquisar)
                    .addComponent(PesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBt)
                    .addComponent(NovoBt)
                    .addComponent(AlterarBt)
                    .addComponent(ExcluirBt)
                    .addComponent(SalvarBt))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBtActionPerformed
        // TODO add your handling code here:
      if(salvarAlterar.equals("salvar")){
      this.salvarProduto();
      }else if(salvarAlterar.equals("alterar")){
          this.alterarProduto();
      }
      
    }//GEN-LAST:event_SalvarBtActionPerformed

    private void NovoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoBtActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(true);
        salvarAlterar = "salvar";
        
    }//GEN-LAST:event_NovoBtActionPerformed

    private void ExcluirBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtActionPerformed
        // TODO add your handling code here:
        int linha = Tabela.getSelectedRow();
        int codigoProduto = (int) Tabela.getValueAt(linha, 0);
        
        if(controllerProdutos.excluirProdutoController(codigoProduto)){
            JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!","ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ExcluirBtActionPerformed

    private void CancelarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtActionPerformed
        // TODO add your handling code here:
        habilitarDesabilitarCampos(false);
        limparCampo();
    }//GEN-LAST:event_CancelarBtActionPerformed

    private void AlterarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarBtActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        int linha = this.Tabela.getSelectedRow();
        try{
            int codigoProduto = (int) this.Tabela.getValueAt(linha, 0);
            habilitarDesabilitarCampos(true);
            modelProdutos = controllerProdutos.retornarProdutoController(codigoProduto);
            this.CodigoTxt.setText(String.valueOf(modelProdutos.getIdProduto()));
            this.NomeTxt.setText(modelProdutos.getProNome());
            this.EstoqueTxt.setText(String.valueOf(modelProdutos.getProEstoque()));
            this.ValorTxt.setText(String.valueOf(modelProdutos.getProValor()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!","ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AlterarBtActionPerformed

    private void PesquisarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarBtActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.Tabela.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.Tabela.setRowSorter(classificador);
        String texto = PesquisarTxt.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_PesquisarBtActionPerformed

    private void EstoqueTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstoqueTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstoqueTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }
    
    private void habilitarDesabilitarCampos(boolean condicao){
        NomeTxt.setEnabled(condicao);
        EstoqueTxt.setEnabled(condicao);
        ValorTxt.setEnabled(condicao);
        SalvarBt.setEnabled(condicao);
        
    }
    
    private void limparCampo(){
        NomeTxt.setText("");
        EstoqueTxt.setText("");
        ValorTxt.setText("");
    }
    
    //Preenche tabela com os produtos do banco de dados.
    private void carregarProdutos(){
        listaModelProduto = controllerProdutos.retornarListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        modelo.setNumRows(0);
        //inserir produtos na tabela
        int cont = listaModelProduto.size();
        for(int i = 0; i < cont; i++){
            modelo.addRow(new Object[]{
                listaModelProduto.get(i).getIdProduto(),
                listaModelProduto.get(i).getProNome(),
                listaModelProduto.get(i).getProEstoque(),
                listaModelProduto.get(i).getProValor()
                });
        }
    }
    
    private void salvarProduto(){
        modelProdutos.setProNome(this.NomeTxt.getText());
        modelProdutos.setProEstoque(Integer.parseInt(this.EstoqueTxt.getText()));
        modelProdutos.setProValor(formatador.converterVirgulaParaPonto(this.ValorTxt.getText()));
        if(controllerProdutos.salvarProdutoController(modelProdutos)>0){
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!","ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampo();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void alterarProduto(){
        modelProdutos.setProNome(this.NomeTxt.getText());
        modelProdutos.setProEstoque(Integer.parseInt(this.EstoqueTxt.getText()));
        modelProdutos.setProValor(formatador.converterVirgulaParaPonto(this.ValorTxt.getText()));
        if(controllerProdutos.alterarProdutoController(modelProdutos)){
            JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!","ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampo();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao alterar produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarBt;
    private javax.swing.JButton CancelarBt;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField CodigoTxt;
    private javax.swing.JLabel Estoque;
    private javax.swing.JFormattedTextField EstoqueTxt;
    private javax.swing.JButton ExcluirBt;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeTxt;
    private javax.swing.JButton NovoBt;
    private javax.swing.JLabel Pesquisar;
    private javax.swing.JButton PesquisarBt;
    private javax.swing.JTextField PesquisarTxt;
    private javax.swing.JButton SalvarBt;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel Valor;
    private javax.swing.JFormattedTextField ValorTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
