<?php
require_once("Andorinha.php");
require_once("Cao.php");
require_once("Cavalo.php");
require_once("Elefante.php");
require_once("Galinha.php");
require_once("Gato.php");
require_once("Pato.php");
?>